
sudo: false
language: node_js
node_js: 12

# 先测试
script:
  - npm run test

after_success:
  - jest --coverage
  # 发布到coverage
  - cat ./src/__test__/coverage/lcov.info | ./node_modules/.bin/coveralls -repotoken $REPO_TOKEN
  # 删除测试生成的代码
  - rm -rf ./src/__test__/coverage

# 部署相关
before_deploy:
  - npm run build # 生成npm包，生成doc文档页
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    skip_cleanup: true # 在运行测试之后且在发行之前，Travis CI会清理所有其他文件和所做的更改， 默认false标识要清理
    on:
      tags: true
    tag: latest # 给npm包添加版本
  - provider: pages
    local_dir: "./docs"
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true

branches:
  only:
  # - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # 只在tag分支时候才会build
  - master